// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadHosts() {
  return window['go']['main']['Host']['ReadHosts']();
}

export function ReadHostsFromNetwork() {
  return window['go']['main']['Host']['ReadHostsFromNetwork']();
}

export function SetPollInterval(arg1) {
  return window['go']['main']['Host']['SetPollInterval'](arg1);
}

export function StopPoll() {
  return window['go']['main']['Host']['StopPoll']();
}

export function System() {
  return window['go']['main']['Host']['System']();
}

export function WriteHosts(arg1) {
  return window['go']['main']['Host']['WriteHosts'](arg1);
}
