// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadHosts():Promise<string>;

export function ReadHostsFromNetwork():Promise<string>;

export function SetPollInterval(arg1:number):Promise<number>;

export function StopPoll():Promise<void>;

export function System():Promise<string>;

export function WriteHosts(arg1:string):Promise<void>;
